### ISSUE TITLE
Does not work after WebStorm upgrade

### ISSUE THREAD

**Issue by TMantas** [jiaolong1021/ElementPlugin#4]
I'm using WebStorm 2018.3 and it does not work (or at least does not work fully).

**Comment by jiaolong1021** [comment]
what part it does not work. please write detail.
![image](https://user-images.githubusercontent.com/13686859/49777868-38a57500-fd3d-11e8-8626-a36ca4aaac92.png)
it works in 
![image](https://user-images.githubusercontent.com/13686859/49777884-5246bc80-fd3d-11e8-8b33-c0ca94d7d164.png)

**Comment by TMantas** [comment]
Hmm, the autocomplete seems to be working. But webstorm does not recognize element UI tags. I think it was working before.
![image](https://user-images.githubusercontent.com/6958890/49801635-639ac380-fd53-11e8-965e-33649b46b50c.png)

**Comment by jiaolong1021** [comment]
element UI tags is not standard html tag, so IDE webstorm doesn't recognize. if you remove the plugin, webstorm also doesn't recognize too.
